apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}-gluetun-tests
  labels:
    app: {{ .Values.name }}
    service: "gluetun"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: gluetun-egress
      image: busybox
      command: ['wget']
      args: ['https://wikipedia.org']
  restartPolicy: Never