@startuml Media Server High-Level Architecture Overview
title Media Server High-Level Architecture Overview

package Frontend{
    [Jellyfin]
    [Jellyseerr]
    [Requestrr]
    () GluetunFrontend 
    () Tailscale
}

package Middleware{
    [Sonarr]
    [Radarr]
    [Bazarr]
    () GluetunMiddleware
}

package Backend{
    [Jackett]
    [Qbittorrent]
    () GluetunBackend
}

Jackett <.[#red]. Sonarr
Jackett <.[#red]. Radarr
Qbittorrent <.[#red]. Sonarr
Qbittorrent <.[#red]. Radarr
Jackett <--> GluetunBackend
Qbittorrent <--> GluetunBackend

Bazarr --> Sonarr
Bazarr --> Radarr

Bazarr <--> GluetunMiddleware
Sonarr <--> GluetunMiddleware
Radarr <--> GluetunMiddleware

Jellyseerr ..> Jellyfin
Jellyseerr .[#green].> Sonarr
Jellyseerr .[#green].> Radarr
Requestrr .[#green].> Sonarr
Requestrr .[#green].> Radarr

Requestrr <--> GluetunFrontend
Jellyseerr <--> GluetunFrontend
Jellyfin <--> GluetunFrontend

Tailscale --> Jellyfin
Tailscale --> Jellyseerr
GluetunFrontend <--> Tailscale

GluetunBackend <-[#blue]-> Internet: tunneled
GluetunMiddleware <-[#blue]-> Internet: tunneled
GluetunFrontend <-[#blue]-> Internet: tunneled

@enduml