apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - name: "jellyfin"
      protocol: TCP
      port: 8096
      targetPort: {{ .Values.service.jellyfin.port }}
