apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-requestrr
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: "requestrr"
          image: "darkalfx/requestrr:latest"
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.requestrr.port }}