@startuml Media Server Network Architecture 
title Media Server Network Architecture 

() Internet
() VPN
() Client
() "Tailscale - client"

package LAN{

    package "Kubernetes Pods"{
        [Jellyfin]
        [Jellyseerr]
        [Jackett]
        [Sonarr]
        [Radarr]
        [Qbittorrent]
        [Requestrr]
        () Gluetun
        () "Tailscale - server"
    }

    ' Egress for some sensitive services over VPN
    Gluetun --> VPN
    VPN --> Internet
    Qbittorrent --> Gluetun
    Jackett --> Gluetun

    ' Egress for other services 
    Jellyfin --> Gluetun
    Jellyseerr --> Gluetun
    Sonarr --> Gluetun
    Radarr --> Gluetun
    Requestrr --> Gluetun

    Sonarr --> Jackett
    Radarr --> Jackett
    Sonarr --> Qbittorrent
    Radarr --> Qbittorrent

    Requestrr --> Sonarr
    Requestrr --> Radarr

    Jellyseerr --> Jellyfin
    Jellyseerr --> Sonarr
    Jellyseerr --> Radarr

    ' Ingress to all services locally
    Client --> "Tailscale - client"
    "Tailscale - client" --> "Tailscale - server"
    "Tailscale - server" --> Jellyfin
    "Tailscale - server" --> Jellyseerr
    "Tailscale - server" --> Jackett
    "Tailscale - server" --> Sonarr
    "Tailscale - server" --> Radarr
    "Tailscale - server" --> Qbittorrent
    "Tailscale - server" --> Requestrr
}


@enduml